language: node_js
node_js:
- '6'
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: sfBNdOfVvEcg0uJS3JgJBIM38S9oNcFoJZaM8OK8rYZXi1TJBYmmfz1hCopVI6yRgPRi+h041scMBgkQnckG5L1+1wwHJb/UlLxf8QtZak1Q6KHlX+VmVztYgxAnxQTbPTss3Pd61fweGjB1dy53cy+pkrLMkSSMxfHcX8i9A5hVAm6HbvWCNe82wQv3mB0NcWmF9q34htmz5s44TUspWjfxjaT0dO0UxLA5uIQdx9XikwH0s4oGk7W+b6EVtSLYhcuokaDASACCAzR96a/3VWUDZ3ootLcPIernYMc1C5QoYrgQxZLRJAdhUL9fxfojxzV/ag6p6KGrCDaefGQRQfezlDBqttOUANr/1p0TU9h3GJznDZjZ2e+xfr73crwbPOZE8lzfrJk4aQ1Zxdo5sH79v/l5q+BOB8T8RgMnKwB87LQupqkCYP6sKTGkshMOOZsLkybxV54vSoTf24MjxfKNb/TN2PFUlz7FdYP5WMBK3/dlmd7f42CLX6BMJbFt6k9yuSMdO9DAz0ut77+FAbFTtAqLbSwtXFvhpMPei6CCsAKxHx9lCqP8+9UD/+3NR4V8phHN+WYUsWyzG1OYfqCY5I29vhiWoRUG8LCHy6otsTm5VlzgtzLcFLOzYY47tUplS4bNq2V7dxnUmT2ss4TVKw3PW27jhi9hLNSgCT8=
  app: jalgoarena-data
  on:
    repo: spolnik/JAlgoArena-Data
